package com.example.SpringCrud.service;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RequestBody;

import com.example.SpringCrud.StudentRepository;
import com.example.SpringCrud.entity.Student;

// TODO: Auto-generated Javadoc
/**
 * The Class StudentService.
 */
@Service
public class StudentService {
	
	/** The student repository. */
	@Autowired
	private StudentRepository studentRepository;
	
	/**
	 * Creates the student.
	 *
	 * @param student the student
	 * @return the map
	 */
	public Map<String, Object> createStudent(@RequestBody Student student){
		Map<String, Object> result = new HashMap<String, Object>();
		try{
			Student found = studentRepository.findStudentByEmail(student.getEmail());
			if(found == null){
				Student created = studentRepository.save(student);
				result.put("responseMessage", "success");
				result.put("successMessage", "Student data is saved successfully. The sudentId generated by system is"+ created.getStudentId() +". Please keep it for future reference.");
			}else{
				result.put("responseMessage", "error");
				result.put("errorMessage", "A student already registered with email "+ student.getEmail() +". Please use different email.");
			}
		}catch(Exception exception){
			result.put("responseMessage", "error");
			result.put("errorMessage", "Something went wrong plase try after sometimes.");
		}
		return result;
	}
}
